imports:
    - { resource: security.yml }

aequasi_cache:
    instances:
        default:
          persistent: true
          namespace: mc
          type: memcached
          hosts:
              - { host: localhost, port: 11211 }